export const BIBLE_BOOKS = [
  // Escrituras Hebreoarameas (Antiguo Testamento)
  { id: 'gen', n: 'Génesis', ch: 50, ot: true },
  { id: 'exo', n: 'Éxodo', ch: 40, ot: true },
  { id: 'lev', n: 'Levítico', ch: 27, ot: true },
  { id: 'num', n: 'Números', ch: 36, ot: true },
  { id: 'deu', n: 'Deuteronomio', ch: 34, ot: true },
  { id: 'jos', n: 'Josué', ch: 24, ot: true },
  { id: 'jue', n: 'Jueces', ch: 21, ot: true },
  { id: 'rut', n: 'Rut', ch: 4, ot: true },
  { id: '1sa', n: '1 Samuel', ch: 31, ot: true },
  { id: '2sa', n: '2 Samuel', ch: 24, ot: true },
  { id: '1re', n: '1 Reyes', ch: 22, ot: true },
  { id: '2re', n: '2 Reyes', ch: 25, ot: true },
  { id: '1cr', n: '1 Crónicas', ch: 29, ot: true },
  { id: '2cr', n: '2 Crónicas', ch: 36, ot: true },
  { id: 'esd', n: 'Esdras', ch: 10, ot: true },
  { id: 'neh', n: 'Nehemías', ch: 13, ot: true },
  { id: 'est', n: 'Ester', ch: 10, ot: true },
  { id: 'job', n: 'Job', ch: 42, ot: true },
  { id: 'sal', n: 'Salmos', ch: 150, ot: true },
  { id: 'pro', n: 'Proverbios', ch: 31, ot: true },
  { id: 'ecl', n: 'Eclesiastés', ch: 12, ot: true },
  { id: 'can', n: 'Cantares', ch: 8, ot: true },
  { id: 'isa', n: 'Isaías', ch: 66, ot: true },
  { id: 'jer', n: 'Jeremías', ch: 52, ot: true },
  { id: 'lam', n: 'Lamentaciones', ch: 5, ot: true },
  { id: 'eze', n: 'Ezequiel', ch: 48, ot: true },
  { id: 'dan', n: 'Daniel', ch: 12, ot: true },
  { id: 'ose', n: 'Oseas', ch: 14, ot: true },
  { id: 'joe', n: 'Joel', ch: 3, ot: true },
  { id: 'amo', n: 'Amós', ch: 9, ot: true },
  { id: 'abd', n: 'Abdías', ch: 1, ot: true },
  { id: 'jon', n: 'Jonás', ch: 4, ot: true },
  { id: 'miq', n: 'Miqueas', ch: 7, ot: true },
  { id: 'nah', n: 'Nahúm', ch: 3, ot: true },
  { id: 'hab', n: 'Habacuc', ch: 3, ot: true },
  { id: 'sof', n: 'Sofonías', ch: 3, ot: true },
  { id: 'hag', n: 'Hageo', ch: 2, ot: true },
  { id: 'zac', n: 'Zacarías', ch: 14, ot: true },
  { id: 'mal', n: 'Malaquías', ch: 4, ot: true },

  // Escrituras Griegas Cristianas (Nuevo Testamento)
  { id: 'mat', n: 'Mateo', ch: 28, ot: false },
  { id: 'mar', n: 'Marcos', ch: 16, ot: false },
  { id: 'luc', n: 'Lucas', ch: 24, ot: false },
  { id: 'jua', n: 'Juan', ch: 21, ot: false },
  { id: 'hch', n: 'Hechos', ch: 28, ot: false },
  { id: 'rom', n: 'Romanos', ch: 16, ot: false },
  { id: '1co', n: '1 Corintios', ch: 16, ot: false },
  { id: '2co', n: '2 Corintios', ch: 13, ot: false },
  { id: 'gal', n: 'Gálatas', ch: 6, ot: false },
  { id: 'efe', n: 'Efesios', ch: 6, ot: false },
  { id: 'fil', n: 'Filipenses', ch: 4, ot: false },
  { id: 'col', n: 'Colosenses', ch: 4, ot: false },
  { id: '1ts', n: '1 Tesalonicenses', ch: 5, ot: false },
  { id: '2ts', n: '2 Tesalonicenses', ch: 3, ot: false },
  { id: '1ti', n: '1 Timoteo', ch: 6, ot: false },
  { id: '2ti', n: '2 Timoteo', ch: 4, ot: false },
  { id: 'tit', n: 'Tito', ch: 3, ot: false },
  { id: 'flm', n: 'Filemón', ch: 1, ot: false },
  { id: 'heb', n: 'Hebreos', ch: 13, ot: false },
  { id: 'san', n: 'Santiago', ch: 5, ot: false },
  { id: '1pe', n: '1 Pedro', ch: 5, ot: false },
  { id: '2pe', n: '2 Pedro', ch: 3, ot: false },
  { id: '1jn', n: '1 Juan', ch: 5, ot: false },
  { id: '2jn', n: '2 Juan', ch: 1, ot: false },
  { id: '3jn', n: '3 Juan', ch: 1, ot: false },
  { id: 'jud', n: 'Judas', ch: 1, ot: false },
  { id: 'apo', n: 'Apocalipsis', ch: 22, ot: false }
];
